dist: trusty
language: java
jdk: oraclejdk8
services:
  - mysql
before_install:
  - chmod +x mvnw
  - mysql -e 'CREATE DATABASE acmevolardb;'
addons:
  sonarcloud:
    organization: "acme-volar"
    token:
      secure: "K9QnkbWnebVqC6GSk94fikC0iofXDKx27aQoZxP8guzoHhPVXn0ZNPqtOdQL2MzlQn0DIcB2/BxVLFjzkPq2VU+OS8Z9D+MclqAx8NwL2I4Vkt0Oxn0kCq2yanszl6owk62ke9e3vFfRciitoVrWEPfFhJEGSKOsYUi/fBfZarAU3K5LUgKCteVJ9CLIiLoLk6KiJE1/CLTm6phaCReq9SxmWV8RMwludTQIcHulH9ZU9VetYAxupyAUHiFPdQh5bGpiSBv3fZik1d4IV3aQjO1W5Gm4DDb00SyQGqtDgEuRAefIQ4YVHTdVyVgfFk0pZ4esGtIiAB8dkhS7Q6RsOFkG00bsKWImgzpZNgPPmOpajR+en4kX7MqK6VXdYWMfS0uW8zXAUkFss6oWCSFsUiOm1oJVQQ/aKelLyBK3Ai2jm7Sm6thc8WYdDTWITuAqlwqIqnxFU4m4rL6+Rhr/K+ri4+/JZ9wEu/cfFMBclcqOfplaMYMAoA1mnPrqJbgyMI55276Lv/+GIoiqaKrZLUU/ES7JAYkBOa8g2WUGSDoNvPSmpUW6091+x/lKrkf1hdeaZaDkGQIC7nyAiloFAIKsjxrXqv/Gn/HsECFtYwapC/TgzorwTNaB17zVu8Xmf8I43+sADKKyvp5zZw7S/yqn/YESULNEHNE/jbrwcUk="

script:
  - mvn test -Dspring.profiles.active=mysql-travis
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=edubotdom_acme-volar
